BEGIN;
CREATE TABLE IF NOT EXISTS public.crm_intake_contacts (
 id text PRIMARY KEY,
 source_number text NOT NULL,
 source_contact_id text NOT NULL,
 display_name text,
 phone text NOT NULL,
 classification text,
 status text NOT NULL DEFAULT 'Pending Review',
 first_message_at timestamptz,
 last_message_at timestamptz,
 last_message_preview text,
 message_count integer NOT NULL DEFAULT 0,
 metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
 promoted_lead_id text REFERENCES public.crm_leads(id),
 created_at timestamptz NOT NULL DEFAULT now(),
 updated_at timestamptz NOT NULL DEFAULT now(),
 UNIQUE(source_number,source_contact_id)
);
CREATE INDEX IF NOT EXISTS crm_intake_contacts_status_idx ON public.crm_intake_contacts(status);
CREATE INDEX IF NOT EXISTS crm_intake_contacts_source_idx ON public.crm_intake_contacts(source_number);
CREATE TABLE IF NOT EXISTS public.crm_intake_messages (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 intake_contact_id text NOT NULL REFERENCES public.crm_intake_contacts(id) ON DELETE CASCADE,
 source_number text NOT NULL,
 provider_message_id text NOT NULL,
 direction text NOT NULL CHECK (direction IN ('Incoming','Outgoing')),
 message_type text NOT NULL DEFAULT 'text',
 body text,
 sender_name text,
 media_urls jsonb,
 media_filenames jsonb,
 message_at timestamptz NOT NULL,
 created_at timestamptz NOT NULL DEFAULT now(),
 UNIQUE(source_number,provider_message_id)
);
CREATE INDEX IF NOT EXISTS crm_intake_messages_contact_idx ON public.crm_intake_messages(intake_contact_id,message_at,id);
COMMIT;