import test from 'node:test';
import assert from 'node:assert/strict';
import {deterministicStatus,evaluationSignals,normalizeStatusSuggestion,statusDecision} from '../src/crm-ai-policy.mjs';
import {runLeadAnalysis,runAiSchedulerBatch} from '../src/crm-ai-orchestrator.mjs';

const workspace=({status='Active Follow-up',messages=[],cursor={},requirements=null,activity=[],followups=[]}={})=>({lead:{id:'L-1',lead_type:status},messages,ai_cursor:cursor,followups,activity,sources:[{source_number:'+919148338801'}],requirement_profile:requirements,ai_runs:[],requirement_evidence:[]});
const msg=(id,direction='Incoming',at='2026-10-02T10:00:00Z')=>({id,direction,message_at:at});

test('incoming message deterministically maps to Waiting on Us',()=>{const x=workspace({status:'New',messages:[msg(9)]});assert.equal(deterministicStatus({lead:x.lead,messages:x.messages}).status,'Waiting on Us');assert.equal(deterministicStatus({lead:x.lead,messages:x.messages}).action,'auto_apply')});
test('outgoing message deterministically maps to Waiting on Customer',()=>{const x=workspace({status:'Active Follow-up',messages:[msg(10,'Outgoing')]});assert.equal(deterministicStatus({lead:x.lead,messages:x.messages}).status,'Waiting on Customer')});
test('high-consequence current statuses are protected',()=>{const x=workspace({status:'Converted',messages:[msg(11)]});assert.equal(deterministicStatus({lead:x.lead,messages:x.messages}).action,'review_required')});
test('evaluation cursor detects delta then settles',()=>{const x=workspace({messages:[msg(12)],cursor:{last_evaluated_message_id:11,last_evaluated_message_at:'2026-10-02T09:00:00Z'}});assert.equal(evaluationSignals({workspace:x,now:new Date('2026-10-02T11:00:00Z')}).reason,'new_reconciled_message');x.ai_cursor.last_evaluated_message_id=12;x.ai_cursor.last_evaluated_message_at='2026-10-02T10:00:00Z';assert.equal(evaluationSignals({workspace:x,now:new Date('2026-10-02T11:00:00Z')}).reason,'no_meaningful_change')});
test('missing confidence or evidence forces review',()=>{const s=normalizeStatusSuggestion({status:'Active Follow-up',reason:'x'});assert.equal(statusDecision({lead:{lead_type:'New'},statusSuggestion:s}).action,'review_required')});
test('safe high-confidence status may auto-apply',()=>{assert.equal(statusDecision({lead:{lead_type:'New'},statusSuggestion:{status:'Waiting on Us',confidence:.9,needs_review:false,evidence_message_ids:[42]}}).action,'auto_apply')});
test('high-consequence recommendation remains review-only',()=>{assert.equal(statusDecision({lead:{lead_type:'Active Follow-up'},statusSuggestion:{status:'Converted',confidence:.99,needs_review:false,evidence_message_ids:[42]}}).action,'review_required')});

test('scheduler skips leads with no meaningful delta without invoking AI',async()=>{const calls=[];const w=workspace({messages:[msg(20)],cursor:{last_evaluated_message_id:20,last_evaluated_message_at:'2026-10-02T10:00:00Z',last_evaluated_at:'2026-10-02T10:00:00Z'}});const repo={async getLeadWorkspace(){return w}};const result=await runLeadAnalysis({repo,leadId:'L-1',invocationSource:'scheduled_6h',analyze:async()=>{calls.push(1)}});assert.equal(result.skipped,true);assert.equal(calls.length,0)});

test('scheduler applies deterministic status and advances evaluation cursor without AI',async()=>{const calls=[];const cursors=[];const activities=[];const w=workspace({status:'New',messages:[msg(21)]});const repo={async getLeadWorkspace(){return w},async updateLead({leadType}){w.lead.lead_type=leadType;return w.lead},async appendActivity(x){activities.push(x)},async setAiEvaluationCursor(x){cursors.push(x)}};const result=await runLeadAnalysis({repo,leadId:'L-1',invocationSource:'scheduled_6h',analyze:async()=>{calls.push(1)}});assert.equal(result.skipped_ai,true);assert.equal(result.deterministic_status,'Waiting on Us');assert.equal(calls.length,0);assert.equal(cursors.length,1);assert.equal(activities[0].action,'ai.status.deterministic_applied')});

test('eligible scheduler path records AI run, draft and checkpoint',async()=>{const w=workspace({status:'Converted',messages:[msg(22)],cursor:{last_evaluated_message_id:21,last_evaluated_message_at:'2026-10-02T09:00:00Z',last_evaluated_at:'2026-10-02T09:00:00Z'}});let savedRun;const calls=[];const cursor=[];const repo={async getLeadWorkspace(){return w},async findAiRunByIdempotencyKey(){return null},async saveAiRun(args){savedRun={id:'run-22',...args};return savedRun},async appendActivity(){},async saveDraft(args){return{id:'draft-22',...args}},async setAiCursor(x){cursor.push(['ai',x])},async setAiEvaluationCursor(x){cursor.push(['eval',x])},async applyAiStatus(args){savedRun.appliedStatus=args;return{action:'ai.status.auto_applied'}},async getAiRunById(){return savedRun}};const result=await runLeadAnalysis({repo,leadId:'L-1',invocationSource:'scheduled_6h',analyze:async()=>{calls.push(1);return{model:'test-model',provider:'test-provider',proposal:{summary:'ok',reply_draft:'Reply',lead_status_suggestion:{status:'Waiting on Customer',reason:'evidence',confidence:.95,needs_review:false,evidence_message_ids:[22]},evidence:[{message_id:22,body:'evidence'}]},usage:{totalTokens:1}}}});assert.equal(calls.length,1);assert.equal(savedRun.invocationSource,'scheduled_6h');assert.equal(savedRun.idempotencyKey.startsWith('scheduled_6h:L-1:22:'),true);assert.equal(result.draft.id,'draft-22');assert.equal(cursor.length,2);assert.equal(savedRun.appliedStatus.automatic,true)});

test('AI failure persists failed run and does not advance cursor',async()=>{const w=workspace({status:'Converted',messages:[msg(23)],cursor:{last_evaluated_message_id:22,last_evaluated_message_at:'2026-10-02T09:00:00Z'}});const calls=[];const saved=[];const cursor=[];const repo={async getLeadWorkspace(){return w},async findAiRunByIdempotencyKey(){return null},async saveAiRun(args){saved.push(args);return{id:'run-failed',...args}},async appendActivity(){},async setAiCursor(x){cursor.push(x)},async setAiEvaluationCursor(x){cursor.push(x)}};await assert.rejects(runLeadAnalysis({repo,leadId:'L-1',invocationSource:'scheduled_6h',analyze:async()=>{calls.push(1);throw Error('provider failed')}}));assert.equal(calls.length,1);assert.equal(saved[0].status,'failed');assert.equal(cursor.length,0)});

test('idempotent existing run recovers checkpoint without a duplicate AI call',async()=>{const w=workspace({status:'Converted',messages:[msg(24)],cursor:{last_evaluated_message_id:23,last_evaluated_message_at:'2026-10-02T09:00:00Z'}});const cursor=[];const existing={id:'run-24',status:'proposed'};const repo={async getLeadWorkspace(){return w},async findAiRunByIdempotencyKey(){return existing},async setAiCursor(x){cursor.push(['ai',x])},async setAiEvaluationCursor(x){cursor.push(['eval',x])}};const result=await runLeadAnalysis({repo,leadId:'L-1',invocationSource:'scheduled_6h',analyze:async()=>{throw Error('duplicate')}});assert.equal(result.skip_reason,'idempotent_existing_run');assert.equal(cursor.length,2)});

test('scheduler batch continues after one lead failure and records partial result',async()=>{const runs=[];const failures=[];const repo={async recoverStaleAiSchedulerRuns(){},async createAiSchedulerRun(){return{id:'scheduler-1'}},async listAiSchedulerCandidates(){return[{id:'L-1'},{id:'L-2'}]},async getLeadWorkspace(){return workspace({status:'Converted',messages:[msg(30,'Incoming')]})},async updateLead({leadType}){return{lead_type:leadType}},async appendActivity(x){if(x.action==='ai.scheduler.lead_failed')failures.push(x)},async setAiCursor(){},async setAiEvaluationCursor(){},async findAiRunByIdempotencyKey(){return null},async saveAiRun(args){return{id:'run-batch',...args}},async getAiRunById(){return{id:'run-batch',status:'proposed'}},async finishAiSchedulerRun(args){runs.push(args);return{id:'scheduler-1',status:args.status}},};let n=0;const result=await runAiSchedulerBatch({repo,analyze:async()=>{n++;if(n===2)throw Error('boom');return{model:'m',provider:'p',proposal:{summary:'ok',lead_status_suggestion:{status:null,reason:'none',needs_review:true},reply_draft:''},usage:{}}}});assert.equal(result.status,'partial');assert.equal(result.ai_failed,1);assert.equal(failures.length,1);assert.equal(runs[0].status,'partial')});
