import test from 'node:test';
import assert from 'node:assert/strict';
import {classifyDeterministically,DETERMINISTIC_RULE_VERSION} from '../src/crm-deterministic-classifier.mjs';

const msg=(id,direction,body)=>({id,direction,body,message_at:`2026-10-03T10:00:0${id}Z`});

test('two-gate qualification requires customer intent and property evidence',()=>{
 const r=classifyDeterministically({messages:[msg(1,'Incoming','Hi, I am looking for a 2BHK in HSR Layout. Budget 35k.')]});
 assert.equal(r.outcome,'qualified');assert.equal(r.classification_code,'qualified_lead');assert.equal(r.rule_id,'QUAL-02-GATES');assert.equal(r.rule_version,DETERMINISTIC_RULE_VERSION);
});

test('outbound property context plus customer visit intent qualifies',()=>{
 const r=classifyDeterministically({messages:[
  msg(1,'Outgoing','2BHK Apartment in Yemalur, rent 35k. https://maps.app.goo.gl/example'),
  msg(2,'Incoming','Can I visit tomorrow evening?')
 ]});
 assert.equal(r.classification_code,'qualified_lead');
});

test('outbound-only property conversation remains pending',()=>{
 const r=classifyDeterministically({messages:[msg(1,'Outgoing','2BHK Apartment in Yemalur, rent 35k. https://maps.app.goo.gl/example')]});
 assert.equal(r.outcome,'pending');assert.equal(r.classification_code,'pending');
});

test('generic greetings do not force a classification',()=>{
 const r=classifyDeterministically({messages:[msg(1,'Incoming','Hi')]});
 assert.equal(r.outcome,'pending');
});

test('repeated generic greetings can become cold inquiry',()=>{
 const r=classifyDeterministically({messages:[msg(1,'Incoming','Hi'),msg(2,'Incoming','Hello')]});
 assert.equal(r.classification_code,'cold_inquiry');
});

test('known group webhook evidence is a hard exclusion',()=>{
 const r=classifyDeterministically({messages:[msg(1,'Incoming','I need a 2BHK in HSR, budget 40k')] ,webhookEvents:[{id:9,payload:{chat_id:'120363417839208296@g.us'}}]});
 assert.equal(r.classification_code,'group_message');assert.equal(r.outcome,'unqualified');
});

test('known operator identity is a hard exclusion',()=>{
 const r=classifyDeterministically({messages:[msg(1,'Incoming','I need a 2BHK in HSR, budget 40k')],knownIdentityCodes:['agent_partner']});
 assert.equal(r.classification_code,'agent_partner');assert.equal(r.outcome,'unqualified');
});

test('promotion needs multiple deterministic markers',()=>{
 const r=classifyDeterministically({messages:[msg(1,'Incoming','Greetings from SmotPro. We would like to organise a special travel promotion campaign.') ]});
 assert.equal(r.classification_code,'promotion');
});

test('agent language is classified as agent partner',()=>{
 const r=classifyDeterministically({messages:[msg(1,'Incoming','Rohit this side from Magicbricks. Any leads?')]});
 assert.equal(r.classification_code,'agent_partner');
});

test('property listing sent is never generated by the deterministic engine',()=>{
 const examples=[
  {messages:[msg(1,'Outgoing','2BHK in Yemalur, rent 35k')]},
  {messages:[msg(1,'Outgoing','Property Name: 2 BHK Apartment https://maps.app.goo.gl/example')]}
 ];
 for(const input of examples)assert.notEqual(classifyDeterministically(input).classification_code,'property_listing_sent');
});

test('insufficient evidence remains pending',()=>{
 const r=classifyDeterministically({messages:[msg(1,'Incoming','Is this your number?')]});
 assert.equal(r.outcome,'pending');
});


test('live-pattern visit language qualifies',()=>{
 const r=classifyDeterministically({messages:[msg(1,'Incoming','Can we schedule a visit'),msg(2,'Incoming','If you can share the location of flat')]});
 assert.equal(r.classification_code,'qualified_lead');
});

test('live-pattern listing-site customer conversation qualifies without agent false positive',()=>{
 const r=classifyDeterministically({messages:[msg(1,'Incoming','I came across your 2 BHK Apartment listed at Housing.com for 45000 in Yemalur. I am interested in the property.'),msg(2,'Incoming','When can we visit?')]});
 assert.equal(r.classification_code,'qualified_lead');
});

test('live-pattern facebook property link plus customer interest qualifies',()=>{
 const r=classifyDeterministically({messages:[msg(1,'Incoming','https://www.facebook.com/share/p/example'),msg(2,'Incoming','Is this available ?'),msg(3,'Incoming','I am interested and want to have a look tomorrow')]});
 assert.equal(r.classification_code,'qualified_lead');
});

test('live-pattern send me rental request qualifies',()=>{
 const r=classifyDeterministically({messages:[msg(1,'Incoming','Send me rental 1 or 2bhk near helios business park.') ]});
 assert.equal(r.classification_code,'qualified_lead');
});

test('phone number does not become budget evidence',()=>{
 const r=classifyDeterministically({messages:[msg(1,'Outgoing','Please call on this number - 7483350693'),msg(2,'Incoming','Ok')]});
 assert.equal(r.outcome,'pending');assert.equal(r.signals.includes('budget_or_price'),false);
});
