import test from 'node:test';
import assert from 'node:assert/strict';
import {analyzeRealLead,bedrockSettings,ollamaSettings,modelSteering} from '../src/ollama-adapter.mjs';

const env={CRM_REAL_AI_ENABLED:'true',AWS_REGION:'ap-southeast-2',AWS_BEDROCK_MODEL_ID:'au.anthropic.claude-opus-4-6-v1',OLLAMA_BASE_URL:'https://ollama.example',OLLAMA_MODEL:'gpt-oss:20b',OLLAMA_API_KEY:'test-only'};
const lead={id:'L-LIVE-1',display_name:'A',normalized_phone:'+919000000001',status:'New',lead_type:'Active Follow-up',tenant_type:'Not specified',priority:'Medium',operator_notes:''};
const requirements={bhk:'2 BHK',budget:50000,preferred_locations:['Harlur'],pets:'Unknown'};
const messages=[{id:1,direction:'Incoming',body:'Looking for a 2 BHK in Harlur under 50k',message_type:'text',message_at:'2026-09-30T10:00:00Z'},{id:2,direction:'Outgoing',body:'Sure, I can help.',message_type:'text',message_at:'2026-09-30T10:15:00Z'},{id:3,direction:'Incoming',body:'I am still looking.',message_type:'text',message_at:'2026-10-01T10:15:00Z'}];
const proposal={summary:'Customer is still looking.',timeline:{first_customer_message_at:messages[0].message_at,last_customer_message_at:messages[2].message_at,last_operator_message_at:messages[1].message_at},requirement_updates:[],missing_information:['Move-in date'],contradictions:[],lead_status_suggestion:{status:'Active Follow-up',reason:'Customer confirmed they are still looking.'},reply_strategy:'Reactivate and ask for move-in timing.',reply_draft:'Are you still looking for a 2 BHK in Harlur? If yes, what move-in date are you targeting?',evidence:[]};
const fakeBedrock=(content=proposal)=>({send:async(command)=>({output:{message:{content:[{text:JSON.stringify(content)}]}}})});

test('recognizes production provider configuration',()=>{assert.deepEqual(ollamaSettings(env),{ready:true,base:'https://ollama.example',model:'gpt-oss:20b',hasKey:true});assert.deepEqual(bedrockSettings(env),{ready:true,region:'ap-southeast-2',model:'au.anthropic.claude-opus-4-6-v1',profile:''})});
test('steering contains production context and safeguards',async()=>{const s=await modelSteering();for(const phrase of ['EasyFind Property Solutions','East Bengaluru','Housing_Listings','complete chronological conversation','reply_draft','requirement_updates'])assert.ok(s.includes(phrase),phrase)});
test('uses Bedrock first and preserves the complete conversation context',async()=>{let ollamaCalled=false;const result=await analyzeRealLead({lead,requirements,messages,aiHistory:[],cursor:null,evidence:[],env,bedrockClient:fakeBedrock(),fetcher:async()=>{ollamaCalled=true;throw Error('Ollama should not run')}});assert.equal(result.provider,'aws-bedrock');assert.equal(result.model,'au.anthropic.claude-opus-4-6-v1');assert.equal(result.messageCount,3);assert.equal(ollamaCalled,false)});
test('falls back to Ollama when Bedrock fails',async()=>{let request;const result=await analyzeRealLead({lead,requirements,messages,env,bedrockClient:{send:async()=>{throw Error('AccessDeniedException')}},fetcher:async(_url,options)=>{request=JSON.parse(options.body);return{ok:true,json:async()=>({message:{content:JSON.stringify(proposal)}})}}});const payload=JSON.parse(request.messages[1].content);assert.equal(result.provider,'ollama');assert.equal(result.fallbackFrom,'aws-bedrock');assert.match(result.fallbackReason,/AccessDeniedException/);assert.equal(payload.conversation.length,3);assert.equal(payload.timeline.customer_message_count,2);assert.equal(payload.timeline.operator_message_count,1);assert.equal(request.model,'gpt-oss:20b');assert.equal(request.messages[0].content,await modelSteering())});
test('rejects non-TLS remote endpoint even after Bedrock fallback',async()=>assert.rejects(analyzeRealLead({lead,requirements,messages,env:{...env,OLLAMA_BASE_URL:'http://ollama.example'},bedrockClient:{send:async()=>{throw Error('Bedrock unavailable')}},fetcher:async()=>{throw Error('must not call')}}),/Insecure/));
