import test from 'node:test';import assert from 'node:assert/strict';import{analyzeFictionalLead,ollamaSettings,modelSteering}from '../src/ollama-adapter.mjs';
const env={CRM_SYNTHETIC_AI_ENABLED:'true',OLLAMA_BASE_URL:'https://ollama.example',OLLAMA_MODEL:'fictional-model',OLLAMA_API_KEY:'test-only'};
test('requires explicit synthetic gate and known fixture',async()=>{await assert.rejects(analyzeFictionalLead({leadId:'L-1001',env:{}}),/disabled/);await assert.rejects(analyzeFictionalLead({leadId:'real-customer',env}),/Unknown fictional/)});
test('recognizes existing provider configuration names',()=>assert.deepEqual(ollamaSettings(env),{ready:true,base:'https://ollama.example',model:'fictional-model',hasKey:true}));
test('uses server-side key and returns fictional proposal',async()=>{let seen;const fetcher=async(url,options)=>{seen={url:String(url),options};return{ok:true,json:async()=>({message:{content:'{"bhk":2,"location":"Harlur","budget":52000,"uncertainties":["pets"]}'}})}};const result=await analyzeFictionalLead({leadId:'L-1001',env,fetcher});assert.equal(result.fictional,true);assert.equal(result.proposal.bhk,2);assert.equal(seen.options.headers.Authorization,'Bearer test-only');assert.equal(JSON.parse(seen.options.body).stream,false)});
test('rejects non-TLS remote endpoints',async()=>assert.rejects(analyzeFictionalLead({leadId:'L-1001',env:{...env,OLLAMA_BASE_URL:'http://ollama.example'},fetcher:async()=>{throw Error('must not call')}}),/Insecure/));
test('reports provider failure rather than fabricating analysis',async()=>assert.rejects(analyzeFictionalLead({leadId:'L-1001',env,fetcher:async()=>({ok:false,status:503})}),/503/));

test('dedicated steering is compact and describes company, role and human review',async()=>{const steering=await modelSteering();assert.ok(Buffer.byteLength(steering,'utf8')<1700);for(const phrase of ['EasyFind Property Solutions','East Bengaluru','internal lead-analysis assistant','operator','JSON','uncertainties','Housing_Listings'])assert.ok(steering.includes(phrase),phrase)});
test('every provider request includes dedicated steering once, not full repository instructions',async()=>{let request;await analyzeFictionalLead({leadId:'L-1001',env,fetcher:async(_url,options)=>{request=JSON.parse(options.body);return{ok:true,json:async()=>({message:{content:'{"bhk":2,"location":"Harlur","budget":52000,"pets":null,"uncertainties":[]}'}})}}});assert.equal(request.messages.length,2);assert.equal(request.messages[0].content,await modelSteering());assert.ok(Buffer.byteLength(JSON.stringify(request),'utf8')<2600);assert.equal(request.messages[1].role,'user')});
test('fenced hosted-model JSON is accepted without a second provider call',async()=>{let calls=0;const result=await analyzeFictionalLead({leadId:'L-1001',env,fetcher:async()=>{calls++;return{ok:true,json:async()=>({message:{content:'```json\n{"bhk":2,"location":"Harlur","budget":52000,"pets":null,"uncertainties":[]}\n```'}})}}});assert.equal(result.proposal.bhk,2);assert.equal(calls,1)});
