import 'jsr:@supabase/functions-js/edge-runtime.d.ts'
import { createClient } from 'npm:@supabase/supabase-js@2.117.2'
const SOURCE_NUMBER='+919148338801'
const keys=Deno.env.get('SUPABASE_SECRET_KEYS')
const secretKey=keys?JSON.parse(keys).default:Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')
if(!secretKey)throw new Error('Supabase backend secret unavailable')
const supabase=createClient(Deno.env.get('SUPABASE_URL')!,secretKey)
const phone=(v:unknown)=>{const d=String(v??'').split('@')[0].replace(/\D/g,'');return d.length===10?'+91'+d:d.length===11&&d.startsWith('0')?'+91'+d.slice(1):d.length===12&&d.startsWith('91')?'+'+d:null}
const eq=(a:string,b:string)=>{const x=new TextEncoder().encode(a),y=new TextEncoder().encode(b);let z=x.length^y.length;for(let i=0;i<Math.max(x.length,y.length);i++)z|=(x[i%x.length]??0)^(y[i%y.length]??0);return z===0}
async function hash(v:string){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return Array.from(new Uint8Array(d)).map(x=>x.toString(16).padStart(2,'0')).join('')}
function date(v:unknown){const n=Number(v);if(Number.isFinite(n)&&n>0){const d=new Date(n<1e10?n*1000:n);if(Number.isFinite(d.valueOf()))return d.toISOString()}const d=new Date(String(v??''));return Number.isFinite(d.valueOf())?d.toISOString():new Date().toISOString()}
function body(m:any){return m?.text&&typeof m.text==='object'?String(m.text.body??'').trim()||null:null}
async function message(payload:any,m:any,i:number){
 const id=String(m.id??'').trim()||null,p=phone(m.from_me?(m.to??m.chat_id):(m.from??m.chat_id)),dir=m.from_me?'Outgoing':'Incoming',type=String(m.type??'text'),at=date(m.timestamp??payload.timestamp),fp=await hash(JSON.stringify({payload,i,id}));
 const er=await supabase.from('crm_webhook_events').upsert({provider:'whapi',provider_event_id:id,event_type:'messages',source_number:SOURCE_NUMBER,phone:p,direction:dir,message_type:type,payload:m,message_at:at,event_fingerprint:fp,processing_status:'received'},{onConflict:'provider,event_fingerprint'}).select('id').single();if(er.error)throw er.error
 if(!p){await supabase.from('crm_webhook_events').update({processing_status:'processed',processed_at:new Date().toISOString()}).eq('id',er.data.id);return{event_id:er.data.id,status:'received_without_contact'}}
 let {data:c,error:ce}=await supabase.from('crm_contact_classifications').select('*').eq('source_number',SOURCE_NUMBER).eq('phone',p).maybeSingle();if(ce)throw ce
 const sender=String((m.from_me?m.to_name:m.from_name)??m.contact_name??'').trim()||null,b=body(m)
 if(!c){const r=await supabase.from('crm_contact_classifications').insert({source_number:SOURCE_NUMBER,phone:p,classification_code:'pending',classification_label:'Pending classification',classification_source:'pending',status:'pending',evidence:{provenance:'live_whapi_webhook',first_message:b,sender_name:sender},first_seen_at:at,last_seen_at:at}).select('*').single();if(r.error)throw r.error;c=r.data}else{const r=await supabase.from('crm_contact_classifications').update({last_seen_at:at,evidence:{...(c.evidence??{}),last_message:b,sender_name:sender}}).eq('id',c.id).select('*').single();if(r.error)throw r.error;c=r.data}
 const lid=c.status==='promoted'?c.lead_id:null
 const mr=await supabase.from('crm_messages').upsert({lead_id:lid,classification_id:c.id,source_number:SOURCE_NUMBER,provider_message_id:id,source_message_id:id,direction:dir,message_type:type,body:b,sender_name:sender,message_at:at},{onConflict:'source_number,source_message_id',ignoreDuplicates:true}).select('id').maybeSingle();if(mr.error)throw mr.error
 await supabase.from('crm_webhook_events').update({processing_status:'processed',processed_at:new Date().toISOString(),lead_id:lid,message_id:mr.data?.id??null}).eq('id',er.data.id)
 return{event_id:er.data.id,status:lid?'processed':'awaiting_manual_classification',classification:c.classification_code,lead_id:lid,message_id:mr.data?.id??null}
}
Deno.serve(async req=>{if(req.method!=='POST')return Response.json({error:'POST required'},{status:405});const envToken=Deno.env.get('CRM_WHAPI_WEBHOOK_TOKEN')??'';const vr=await supabase.rpc('crm_get_webhook_secret');const vaultToken=typeof vr.data==='string'?vr.data:'';const token=envToken||vaultToken;if(!token||!eq(token,req.headers.get('x-crm-webhook-token')??''))return Response.json({error:'Unauthorized'},{status:401});let payload:any;try{payload=await req.json()}catch{return Response.json({error:'Invalid JSON'},{status:400})};const ms=Array.isArray(payload.messages)?payload.messages.filter((x:any)=>x&&typeof x==='object'):[ ];const results=[];if(ms.length){for(let i=0;i<Math.min(ms.length,100);i++)results.push(await message(payload,ms[i],i))}else{const fp=await hash(JSON.stringify(payload));const r=await supabase.from('crm_webhook_events').upsert({provider:'whapi',provider_event_id:String(payload.id??'').trim()||null,event_type:'unknown',source_number:SOURCE_NUMBER,phone:null,direction:null,message_type:'event',payload,event_fingerprint:fp,message_at:date(payload.timestamp),processing_status:'processed',processed_at:new Date().toISOString()},{onConflict:'provider,event_fingerprint'}).select('id').maybeSingle();if(r.error)return Response.json({error:'event persistence failed'},{status:500});results.push({event_id:r.data?.id??null,status:'event_recorded'})}return Response.json({ok:true,source_number:SOURCE_NUMBER,received_events:results.length,results})})