services:
  - type: web
    name: easyfind-website
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: GOOGLE_PLACES_API_KEY
        sync: false
      - key: SESSION_SECRET
        sync: false
