import {readFile} from 'node:fs/promises';
const steeringUrl=new URL('../steering.md',import.meta.url);
let steeringPromise;
export async function modelSteering(){if(!steeringPromise)steeringPromise=readFile(steeringUrl,'utf8').then(text=>{if(Buffer.byteLength(text,'utf8')>12000||!text.trim())throw Error('Invalid model steering');return text.trim()}).catch(error=>{steeringPromise=null;throw error});return steeringPromise;}
export function ollamaSettings(env){const base=env.OLLAMA_BASE_URL||env.OLLAMA_HOST;const model=env.OLLAMA_MODEL||env.OLLAMA_MODEL_NAME;return {ready:Boolean(base&&model),base,model,hasKey:Boolean(env.OLLAMA_API_KEY)};}
const cleanJson=(raw)=>{const s=String(raw||'').trim();const fenced=s.match(/^\`\`\`(?:json)?\s*([\s\S]*?)\s*\`\`\`$/i);return JSON.parse((fenced?fenced[1]:s).trim())};
const validate=(x)=>{if(!x||typeof x!=='object'||Array.isArray(x))throw Error('Invalid model JSON');const keys=['summary','timeline','requirement_updates','missing_information','contradictions','lead_status_suggestion','reply_strategy','reply_draft','evidence'];for(const k of keys)if(!(k in x))throw Error('Model JSON missing '+k);return x};
export async function analyzeRealLead({lead,requirements,messages,aiHistory=[],cursor=null,evidence=[],env,fetcher=fetch}){
 if(env.CRM_REAL_AI_ENABLED!=='true')throw Error('Real AI disabled');
 if(!lead||typeof lead.id!=='string')throw Error('Invalid lead');
 const config=ollamaSettings(env);if(!config.ready)throw Error('Ollama provider configuration incomplete');
 const steering=await modelSteering();
 const chronological=(messages||[]).map(m=>({id:m.id,direction:m.direction,body:m.body,message_type:m.message_type,sender_name:m.sender_name,message_at:m.message_at,source_message_id:m.source_message_id||m.provider_message_id}));
 const incoming=chronological.filter(m=>m.direction==='Incoming'),outgoing=chronological.filter(m=>m.direction==='Outgoing');
 const first=incoming[0]?.message_at||chronological[0]?.message_at||null,last=chronological.at(-1)?.message_at||null,lastIncoming=incoming.at(-1)?.message_at||null,lastOutgoing=outgoing.at(-1)?.message_at||null;
 const userPayload={task:'Perform a complete lead review and produce an operator-ready draft reply plus evidence-backed requirement updates. The entire supplied conversation is authoritative context; do not claim to know anything outside it.',lead:{id:lead.id,display_name:lead.display_name,phone:lead.normalized_phone,status:lead.status,lead_type:lead.lead_type,tenant_type:lead.tenant_type,priority:lead.priority,operator_notes:lead.operator_notes||''},requirements:requirements||{},conversation:chronological,timeline:{first_message_at:first,first_customer_message_at:incoming[0]?.message_at||null,last_customer_message_at:lastIncoming,last_operator_message_at:lastOutgoing,last_message_at:last,customer_message_count:incoming.length,operator_message_count:outgoing.length},prior_ai_runs:aiHistory,cursor,evidence};
 const endpoint=new URL('/api/chat',config.base);if(endpoint.protocol!=='https:'&&endpoint.hostname!=='localhost'&&endpoint.hostname!=='127.0.0.1')throw Error('Insecure Ollama endpoint');
 const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),60000);
 try{const response=await fetcher(endpoint,{method:'POST',headers:{'Content-Type':'application/json',...(env.OLLAMA_API_KEY?{Authorization:'Bearer '+env.OLLAMA_API_KEY}:{})},body:JSON.stringify({model:config.model,stream:false,format:'json',messages:[{role:'system',content:steering},{role:'user',content:JSON.stringify(userPayload)}]}),signal:controller.signal});if(!response.ok)throw Error('Ollama request failed ('+response.status+')');let body;try{body=await response.json()}catch{throw Error('Provider returned non-JSON HTTP body')}if(typeof body?.message?.content!=='string')throw Error('Provider response shape invalid');const proposal=validate(cleanJson(body.message.content));return{leadId:lead.id,provider:'ollama',model:config.model,proposal,groundedIn:'complete CRM lead conversation and normalized requirement profile',messageCount:chronological.length,timeline:{first,last,lastIncoming,lastOutgoing}}}finally{clearTimeout(timeout)}
}
