import {BedrockRuntimeClient,ConverseCommand} from '@aws-sdk/client-bedrock-runtime';
import {readFile} from 'node:fs/promises';

const steeringUrl=new URL('../steering.md',import.meta.url);
let steeringPromise;
let bedrockClient;
export async function modelSteering(){if(!steeringPromise)steeringPromise=readFile(steeringUrl,'utf8').then(text=>{if(Buffer.byteLength(text,'utf8')>12000||!text.trim())throw Error('Invalid model steering');return text.trim()}).catch(error=>{steeringPromise=null;throw error});return steeringPromise;}
export function ollamaSettings(env){const base=env.OLLAMA_BASE_URL||env.OLLAMA_HOST;const model=env.OLLAMA_MODEL||env.OLLAMA_MODEL_NAME;return {ready:Boolean(base&&model),base,model,hasKey:Boolean(env.OLLAMA_API_KEY)};}
export function bedrockSettings(env){const region=env.AWS_REGION||env.AWS_DEFAULT_REGION||'ap-southeast-2';const model=env.AWS_BEDROCK_MODEL_ID||'au.anthropic.claude-opus-4-6-v1';const fallbackModel=env.AWS_BEDROCK_FALLBACK_MODEL_ID||'au.anthropic.claude-sonnet-4-6';return {ready:Boolean(region&&model),region,model,fallbackModel,profile:env.AWS_PROFILE||''};}
const cleanJson=(raw)=>{const s=String(raw||'').trim();const fence=String.fromCharCode(96,96,96);const fenced=s.match(new RegExp('^'+fence+'(?:json)?\\s*([\\s\\S]*?)\\s*'+fence+'$','i'));return JSON.parse((fenced?fenced[1]:s).trim())};
const validate=(x)=>{if(!x||typeof x!=='object'||Array.isArray(x))throw Error('Invalid model JSON');const keys=['summary','timeline','requirement_updates','missing_information','contradictions','lead_status_suggestion','reply_strategy','reply_draft','evidence'];for(const k of keys)if(!(k in x))throw Error('Model JSON missing '+k);return x};
const usageMetrics=({model,inputTokens=0,outputTokens=0,cacheReadInputTokens=0,cacheWriteInputTokens=0}={})=>{const input=Number.isFinite(Number(inputTokens))?Number(inputTokens):0;const output=Number.isFinite(Number(outputTokens))?Number(outputTokens):0;const cacheRead=Number.isFinite(Number(cacheReadInputTokens))?Number(cacheReadInputTokens):0;const cacheWrite=Number.isFinite(Number(cacheWriteInputTokens))?Number(cacheWriteInputTokens):0;const rates=String(model||'').includes('opus-4-6')?{input:5,output:25,cacheRead:.5,cacheWrite:6.25}:String(model||'').includes('sonnet-4-6')?{input:3,output:15,cacheRead:.3,cacheWrite:3.75}:null;const estimatedCostUsd=rates?((input*rates.input)+(output*rates.output)+(cacheRead*rates.cacheRead)+(cacheWrite*rates.cacheWrite))/1000000:null;return{inputTokens:input,outputTokens:output,totalTokens:input+output,cacheReadInputTokens:cacheRead,cacheWriteInputTokens:cacheWrite,estimatedCostUsd,pricingSource:rates?'standard_public_rates':'unavailable'};};
const buildPayload=({lead,requirements,messages,aiHistory=[],cursor=null,evidence=[]})=>{const chronological=(messages||[]).map(m=>({id:m.id,direction:m.direction,body:m.body,message_type:m.message_type,sender_name:m.sender_name,message_at:m.message_at,source_message_id:m.source_message_id||m.provider_message_id}));const incoming=chronological.filter(m=>m.direction==='Incoming'),outgoing=chronological.filter(m=>m.direction==='Outgoing');const first=incoming[0]?.message_at||chronological[0]?.message_at||null,last=chronological.at(-1)?.message_at||null,lastIncoming=incoming.at(-1)?.message_at||null,lastOutgoing=outgoing.at(-1)?.message_at||null;return{payload:{task:'Perform a complete lead review and produce an operator-ready draft reply plus evidence-backed requirement updates. The entire supplied conversation is authoritative context; do not claim to know anything outside it.',lead:{id:lead.id,display_name:lead.display_name,phone:lead.normalized_phone,status:lead.status,lead_type:lead.lead_type,tenant_type:lead.tenant_type,priority:lead.priority,operator_notes:lead.operator_notes||''},requirements:requirements||{},conversation:chronological,timeline:{first_message_at:first,first_customer_message_at:incoming[0]?.message_at||null,last_customer_message_at:lastIncoming,last_operator_message_at:lastOutgoing,last_message_at:last,customer_message_count:incoming.length,operator_message_count:outgoing.length},prior_ai_runs:aiHistory,cursor,evidence},messageCount:chronological.length,timeline:{first,last,lastIncoming,lastOutgoing}}};
const getBedrockClient=(config)=>{if(!bedrockClient||bedrockClient.__region!==config.region){bedrockClient=new BedrockRuntimeClient({region:config.region});bedrockClient.__region=config.region;}return bedrockClient;};

async function analyzeWithBedrockModel({lead,payload,steering,env,bedrockClient:injectedClient,modelId}){const config=bedrockSettings(env);if(!config.ready)throw Error('AWS Bedrock configuration incomplete');const client=injectedClient||getBedrockClient(config);const command=new ConverseCommand({modelId,messages:[{role:'user',content:[{text:JSON.stringify(payload)}]}],system:[{text:steering}],inferenceConfig:{maxTokens:Number(env.AWS_BEDROCK_MAX_TOKENS||4096),temperature:Number(env.AWS_BEDROCK_TEMPERATURE||0.2)}});const controller=new AbortController();const timeoutMs=Math.max(15000,Math.min(180000,Number(env.CRM_AI_BEDROCK_TIMEOUT_MS||90000)));const timeout=setTimeout(()=>controller.abort(),timeoutMs);let response;try{response=await client.send(command,{abortSignal:controller.signal});}finally{clearTimeout(timeout);}const raw=response?.output?.message?.content?.map(x=>x?.text||'').join('')||'';if(!raw)throw Error('Bedrock response contained no text');const proposal=validate(cleanJson(raw));const usage=usageMetrics({model:modelId,inputTokens:response?.usage?.inputTokens,outputTokens:response?.usage?.outputTokens,cacheReadInputTokens:response?.usage?.cacheReadInputTokens,cacheWriteInputTokens:response?.usage?.cacheWriteInputTokens});return{leadId:lead.id,provider:'aws-bedrock',model:modelId,proposal,usage,groundedIn:'complete CRM lead conversation and normalized requirement profile',messageCount:payload.conversation.length,timeline:{first:payload.timeline.first_message_at,last:payload.timeline.last_message_at,lastIncoming:payload.timeline.last_customer_message_at,lastOutgoing:payload.timeline.last_operator_message_at}};}

async function analyzeWithOllama({lead,payload,steering,env,fetcher}){const config=ollamaSettings(env);if(!config.ready)throw Error('Ollama provider configuration incomplete');const endpoint=new URL('/api/chat',config.base);if(endpoint.protocol!=='https:'&&endpoint.hostname!=='localhost'&&endpoint.hostname!=='127.0.0.1')throw Error('Insecure Ollama endpoint');const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),60000);try{const response=await fetcher(endpoint,{method:'POST',headers:{'Content-Type':'application/json',...(env.OLLAMA_API_KEY?{Authorization:'Bearer '+env.OLLAMA_API_KEY}:{})},body:JSON.stringify({model:config.model,stream:false,format:'json',messages:[{role:'system',content:steering},{role:'user',content:JSON.stringify(payload)}]}),signal:controller.signal});if(!response.ok)throw Error('Ollama request failed ('+response.status+')');let body;try{body=await response.json()}catch{throw Error('Provider returned non-JSON HTTP body')}if(typeof body?.message?.content!=='string')throw Error('Provider response shape invalid');const proposal=validate(cleanJson(body.message.content));const usage=usageMetrics({model:config.model,inputTokens:body?.prompt_eval_count??body?.usage?.prompt_tokens,outputTokens:body?.eval_count??body?.usage?.completion_tokens});return{leadId:lead.id,provider:'ollama',model:config.model,proposal,usage,groundedIn:'complete CRM lead conversation and normalized requirement profile',messageCount:payload.conversation.length,timeline:{first:payload.timeline.first_message_at,last:payload.timeline.last_message_at,lastIncoming:payload.timeline.last_customer_message_at,lastOutgoing:payload.timeline.last_operator_message_at}}}finally{clearTimeout(timeout)}}

export async function analyzeRealLead({lead,requirements,messages,aiHistory=[],cursor=null,evidence=[],env,fetcher=fetch,bedrockClient=null}){if(env.CRM_REAL_AI_ENABLED!=='true')throw Error('Real AI disabled');if(!lead||typeof lead.id!=='string')throw Error('Invalid lead');const steering=await modelSteering();const built=buildPayload({lead,requirements,messages,aiHistory,cursor,evidence});let bedrockError=null;const config=bedrockSettings(env);for(const modelId of [config.model,config.fallbackModel].filter((x,i,a)=>x&&a.indexOf(x)===i)){try{const result=await analyzeWithBedrockModel({lead,payload:built.payload,steering,env,bedrockClient,modelId});if(modelId!==config.model){return{...result,fallbackFrom:config.model,fallbackReason:bedrockError?.message||'Bedrock primary unavailable'}}return result}catch(error){bedrockError=error;console.warn('[crm-ai] Bedrock model failed:',modelId,error?.message||error)}}try{const result=await analyzeWithOllama({lead,payload:built.payload,steering,env,fetcher});return{...result,fallbackFrom:'aws-bedrock',fallbackReason:bedrockError?.message||'Bedrock unavailable'}}catch(ollamaError){throw Error('AI providers failed: Bedrock: '+(bedrockError?.message||'unknown')+'; Ollama: '+(ollamaError?.message||'unknown'))}}
